FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app

COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw

# cache Maven repository so it's not downloaded during every build
RUN --mount=type=cache,target=/root/.m2 ./mvnw -B -DskipTests dependency:go-offline

# copy src
COPY src ./src

# build using cached .m2
RUN --mount=type=cache,target=/root/.m2 ./mvnw -B package

# run
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/eye-tracking-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]